title: My Blog
description: >- # using `>-` to ignore line breaks
  My Blog
baseurl: ""
url: "https://michael-lehn.github.io" # die Basis-URL der Seite

# Build settings
markdown: kramdown
theme: minima

# Exclude files and folders from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins
plugins:
  - jekyll-feed
  - jekyll-environment-variables

# Jekyll Feed settings
feed:
  path: feed.xml

# Permalinks settings
permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"

collections:
  posts:
    output: true
    permalink: /:collection/:path/
  de:
    output: true
    permalink: /de/:collection/:path/
  en:
    output: true
    permalink: /en/:collection/:path/

gitalk:
  repo: 'michael-lehn.github.io`
  owner: 'michael-lehn'
  admin: ['michael-lehn']
  distractionFreeMode: false
