name: Determine Available Ruby Versions

on:
  push:
    branches:
      - main

jobs:
  list-ruby-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List available Ruby versions
        run: ruby -v > available_ruby_versions.txt

      - name: Save Ruby versions
        uses: actions/upload-artifact@v2
        with:
          name: ruby-versions
          path: available_ruby_versions.txt

