name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [ '2.6.9', '2.7.2', '3.0.0' ] # Fügen Sie hier weitere Versionen hinzu, falls nötig

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Display Ruby version
        run: ruby -v

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        env:
          JEKYLL_GITALK_CLIENT_ID: ${{ secrets.JEKYLL_GITALK_CLIENT_ID }}
          JEKYLL_GITALK_CLIENT_SECRET: ${{ secrets.JEKYLL_GITALK_CLIENT_SECRET }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./_site
